#name: 'Vulnerabilities scanning'
#on:
#  push:
#
#jobs:
#  scan:
#    name: Vulnerabilities scan
#    uses: th2-net/.github/.github/workflows/python-scan.yml@python-workflow
#    with:
#       safety-args: '-i 70612' # ignore https://data.safetycli.com/v/70612/97c/. Jinja2 library is not used in our code directly.
