name: 'Vulnerabilities scanning'
on:
  push:

jobs:
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@python-workflow
    with:
      safety-args: '-i 70612'

